# Generated by Django 6.0.5 on 2026-07-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donorresponse',
            options={'managed': True},
        ),
    ]
